// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/pricing" | "/about" | "/login" | "/dashboard";
  };
  "routes/home/page/home.tsx": {
    id: "routes/home/page/home";
    page: "/";
  };
  "routes/pricing/page/pricing.tsx": {
    id: "routes/pricing/page/pricing";
    page: "/pricing";
  };
  "routes/about/page/about.tsx": {
    id: "routes/about/page/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home/page/home": typeof import("./app/routes/home/page/home.tsx");
  "routes/pricing/page/pricing": typeof import("./app/routes/pricing/page/pricing.tsx");
  "routes/about/page/about": typeof import("./app/routes/about/page/about.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
};